version: "3.8"
services:
  api: 
    build: ./api 
    container_name: api_c
    ports: 
      - "5000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules

      #Porque o /app , o nome que você deu ao seu diretório de trabalho, foi criado em /.
  myblog:
    build: ./myblog
    container_name: myblog_c
    ports: 
      - "3000:5173"
    stdin_open: true
    tty: true
    command: npm run dev -- --host